USE flight_data_db;

CREATE TABLE asitrepWPK (
Date VARCHAR(40),
MONTH INT(40),
AEROSTAT_SN VARCHAR(40),
SiteID VARCHAR(40),
TIME INT(40),
SYSTEM_ VARCHAR(10),
FLIGHT_ INT(40),
REASON_ VARCHAR(10),
LAUNCHES INT,
RECOVERIES INT,
FLIGHTS INT(40),
TENSION INT(40),
Winds_Aloft DECIMAL(4,2),
PITCH DECIMAL(4,2),
HELIUM_ DECIMAL(3,2),
BALLONET_ DECIMAL(4,2),
GROUND_ DECIMAL(4,2),
BAROM_ DECIMAL(4,2),
PRIMARY KEY(Date,TIME)
);
